on: [pull_request, push]
permissions:
  contents: write
jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
          - platform: 'ubuntu-latest'
            args: ''
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || ''}}
      - if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - run: pnpm install
      - uses: tauri-apps/tauri-action@dev
        with:
          tagName: app-v__VERSION__
          releaseName: 'Remote Keyboard App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          args: ${{matrix.args}}
